language: ruby

before_install: |
  sudo add-apt-repository -y ppa:fcwu-tw/ppa
  sudo apt-get update
  sudo apt-get install -y vim

before_script:
  git clone https://github.com/junegunn/vader.vim.git test/vader/vader.vim

script: test/vader/run

