language: ruby

os:
  - linux

install:
  - sudo add-apt-repository -y ppa:fcwu-tw/ppa
  - sudo apt-get -qq update
  - sudo apt-get -qq -f install
  - sudo apt-get -qq install vim

before_script:
  - git clone https://github.com/junegunn/vader.vim.git

script:
  - vim --version
  - vim -Nu <(cat << VIMRC
    let &rtp  =  '.,' . &rtp
    let &rtp .= ',after'
    let &rtp .= ',vader.vim'
    filetype plugin indent on
    syntax enable
    VIMRC) -c 'Vader! test/vader/*' > /dev/null

