language: ruby

sudo: false

env:
  global:
    - DEPS=$HOME/deps
    - PATH=$DEPS/bin:$PATH

install: |
  git clone --depth 1 https://github.com/vim/vim
  cd vim
  ./configure --prefix=$DEPS --with-features=huge
  make
  make install
  cd -

before_script:
  git clone https://github.com/junegunn/vader.vim.git test/vader/vader.vim

script: test/vader/run

