language: vim

# before_install:
#   - sudo add-apt-repository -y ppa:nmi/vim-snapshots
#   - sudo apt-get -qq update
#   - sudo apt-get -qq install vim

before_script: |
  sudo apt-get -y update
  sudo apt-get -y install vim
  git clone https://github.com/junegunn/vader.vim.git test/vader/vader.vim

script: test/vader/run

