name: CI tests

on: push

jobs:
  make-tests:
    name: Makefile tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]

    steps:
    - uses: actions/checkout@master
    - name: Run Makefile tests with neovim
      run: make -C test/features/completion
    - name: Run Makefile tests with Vim
      run: make MYVIM="vim -T dumb --noplugin -n" -C test/features/completion

  vader-tests:
    name: Vader tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]

    steps:
    - uses: actions/checkout@master
    - name: Clone vader.vim
      run: git clone https://github.com/junegunn/vader.vim.git test/vader/vader.vim
    - name: Run Vader tests
      run: test/vader/run
