name: CI tests

on:
  push:
    paths-ignore:
      - 'doc/*'
      - 'docker/*'
      - 'media/*'
      - '.github/**'
      - '*.md'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Install general dependencies
      run: |
        sudo apt update
        sudo apt install neovim
        sudo apt install texlive texlive-latex-extra
        sudo apt install latexmk
        sudo apt install gcc moreutils
        sudo apt install libmodule-build-perl
        sudo apt install libconfig-autoconf-perl
        sudo apt install libextutils-libbuilder-perl
    - name: Install bibparse
      run: |
        wget https://search.cpan.org/CPAN/authors/id/A/AM/AMBS/Text-BibTeX-0.85.tar.gz
        tar zxf Text-BibTeX-0.85.tar.gz
        cd Text-BibTeX-0.85
        perl Build.PL
        ./Build
        sudo ./Build install
    - name: Run tests with neovim
      run:
        cd test/tests
        make -j1
    # - name: Run tests with vim
    #   run:
    #     cd test/tests
    #     make -j1 MYVIM="vim -T dumb --not-a-term --noplugin -n"
