name: CI tests

on:
  push:
    paths-ignore:
      - 'doc/*'
      - 'docker/*'
      - 'media/*'
      - '.github/**'
      - '*.md'

jobs:
  make-tests-neovim:
    name: Makefile tests on latest Ubuntu with neovim
    runs-on: ubuntu-latest
    #ubuntu-18.04
    #ubuntu-16.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Install general dependencies
      run: |
        sudo apt update
        sudo apt install neovim
        sudo apt install texlive{,-latex-extra}
        sudo apt install latexmk
        sudo apt install gcc moreutils
        sudo apt install lib{module-build,config-autoconf,extutils-libbuilder}-perl
    - name: Install bibparse
      run: |
        wget https://search.cpan.org/CPAN/authors/id/A/AM/AMBS/Text-BibTeX-0.85.tar.gz
        tar zxf Text-BibTeX-0.85.tar.gz
        cd Text-BibTeX-0.85
        perl Build.PL
        ./Build
        sudo ./Build install
    - name: Run tests with neovim
      run: cd test/tests && make -j1

  # make-tests-vim:
  #   name: Makefile tests on Ubuntu 16.04 with Vim
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Install dependencies
  #     run: sudo apt install texlive libtext-bibtex-perl
  #   - name: Run tests with Vim
  #     run: make MYVIM="vim -T dumb --not-a-term --noplugin -n" -C test/features/completion
